# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d578d1ee66eac3c1c530cb547df8093c36ab0defa4fc02c11d8f97e21816db9fbf3f997915d219c74e0067e581146b16229e3bc7b031b782bc3bae92c6f84c1d

test:
  secret_key_base: 653828828d4e9b4db93436ba1b668ef95827da04f02655c2f7a826b29804ccce6068186d1403b1f398814cb4d3264cb68daf095eb1b947cac8f2a1e49882909d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
